Add dataset, preprocess and pointnet2
jina-ai/executor-3d-encoder pull request #15
Opened 2022-08-06 12:03 UTC by elenacliu

Here is the modification of the structure. There are still some bugs in my pointnet2 codes. 
I will solve the possible problems after you comment.

@numb3r3 @jemmyshin

2022-08-09 13:17 UTC, elenacliu commented
I have fixed the bugs in pointnet2 now.

2022-08-12 08:13 UTC, jemmyshin requested changes

2022-08-12 08:13 UTC, jemmyshin commented on executor/encoder_pl.py
> +        default_model_name='pointconv',
I prefer to set this as a global variable like:  ``DEFAULT_MODEL_NAME=pointconv``because this is not a property of the encoder instance, rather it's a constant for now.

2022-08-12 08:13 UTC, jemmyshin commented on executor/encoder_pl.py
> +        if model_path:
what if `model_path` is `None`? Should we raise any exceptions to users?

2022-08-12 08:13 UTC, jemmyshin commented on executor/encoder_pl.py
> +        logits = self(x)
`self._model(x)` ?

2022-08-12 08:13 UTC, jemmyshin commented on executor/encoder_pl.py
> +class MeshDataEncoderPL(pl.LightningModule):
Move this class into `datasets/models` since this is only a training script, not a executor

2022-08-19 02:57 UTC, elenacliu commented on executor/encoder_pl.py
> +        if model_path:
if `model_path` is `None`, self._model is just an initialized MeshDataModel instance without downloading the pretrained model from the https:// network.

2022-08-19 03:58 UTC, jemmyshin approved these changes
LGTM!

2022-08-19 04:25 UTC, merged